frameworkVersion: ">=2.30.0 <3.0.0"
service: clean-aws-code-storage

plugins:
    - ./vendor/bref/bref

provider:
    name: aws
    region: eu-central-1
    runtime: provided.al2
    lambdaHashingVersion: 20201221

    iam:
        role:
            statements:
              - Effect: Allow
                Action:
                    - lambda:ListFunctions
                    - lambda:ListVersionsByFunction
                    - lambda:DeleteFunction
                Resource:
                    - "*"

functions:
    app:
        handler: src/index.php
        timeout: 900
        description: "See https://github.com/Nyholm/clean-aws-lambda-code-storage"
        layers:
            - ${bref:layer.php-80}
        events:
            - schedule:
                  rate: rate(7 days)
                  input:
                      save: 5 # Save 5 versions
                      # By default, we are only checking the current region. You
                      # may also specify regions by uncomment the line below.
                      #regions: eu-west-1 eu-central-1 us-east-1
